VERSION 4.00
Begin VB.MDIForm MDIForm1 
   BackColor       =   &H8000000C&
   Caption         =   "MDIForm1"
   ClientHeight    =   20070
   ClientLeft      =   13980
   ClientTop       =   2475
   ClientWidth     =   6720
   Height          =   20475
   Left            =   13920
   LinkTopic       =   "MDIForm1"
   Top             =   2130
   Width           =   6840
End
Attribute VB_Name = "MDIForm1"
Attribute VB_Creatable = False
Attribute VB_Exposed = False
